### ISSUE TITLE
Regions Unexplored (forge/fabric) update breaking existing worlds due to block name changes

### ISSUE THREAD

**Issue by Linkmaster007** [LunaPixelStudios/Prominence#182]
### Describe the Bug

Due to an update from the creator of Regions Unexplored (forge/fabric) and swapping the names of a bunch of blocks (ref this post: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/28 ) a lot of generated worlds are broken now. 

Any way you guys could roll back the update on this mod unless you can go over the new name of every block the mod creator changed (which they did not list)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.3.1

### Optifine

No

**Comment by nvb-uy** [comment]
We've swapped the blocks in the prior update so players wouldn't have issues, it seems like you skipped that update which means your world is like this. Grab your world's backup and use it with the prior update so you can replace the blocks, then update to the latest

**Comment by PotatoDotJar** [comment]
I have a server that we created on v1.2.0. We then updated to v1.3.0hf (since 1.3.0 and 1.3.0hf came out the same day) and now our biomes are bricked. We never ran our server on v1.1.0hf and there was no notice of this on the modpack page. Only the changelog for v1.1.0hf mentions the biome issue.

The changelog for v1.3.0 does not mention any warnings or mention of the potential for this other than "Disabled known state generation from block swap (Should decrease storage usage by a lot)" which seems unrelated so I am not sure how we (as players of this modpack) could have prevented this.

**A breakdown of each version of Prominence II as downloaded from Curseforge**

Prominence II v1.2.0: (Region Unexplored version is https://www.curseforge.com/minecraft/mc-mods/regions-unexplored/files/4583966 - 0.4.1)
      "projectID": 659110,
      "fileID": 4583966,
      "required": true
Prominence II v1.3.0: (Region Unexplored version is https://www.curseforge.com/minecraft/mc-mods/regions-unexplored/files/4747162 - 0.5.2)
      "projectID": 659110,
      "fileID": 4747162,
      "required": true
Prominence II v1.3.0hf:
      "projectID": 659110,
      "fileID": 4747162,
      "required": true

Region Unexplored mod says: "NOTICE: DUE TO THE SIZE OF THE 0.5.0 UPDATE AND THE AMOUNT OF CHANGES THINGS MAY NOT FUNCTION CORRECTLY IN OLD RU WORLDS (ie. Blocks that were removed/renamed disappearing, removed/renamed biomes reverting to plains). I'd highly suggest starting a new world for this update or using Blockswap mod to replace the changed/removed blocks on load."

Nothing in the change log from 1.3.0 (the one version we've skipped) that says anything about the blockswap or regions unexplored mod being updated which is what appears to have broken our world after updating from v1.2.0 to v1.3.0hf. 

I don't understand how you can say skipping an update would have caused this when the mod that actually broke this was introduced in v1.3.0.
