### ISSUE TITLE
Game crashes when right clicking scribe table with spell  book (Ars Nouveau)

### ISSUE THREAD

**Issue by AkutoA** [LunaPixelStudios/Prominence#234]
### Describe the Bug

Game crashes when right clicking scribe table with spell book

### Reproduction Steps

1. Place the scribe's table down
2. Right click table with the tier 1 or tier 2 spell book (Only 2 I tested it with)
3. Crash
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/Prominence/assets/148004071/793e901b-43e6-4bf7-87f6-ff802fda3886

### Crash Report or Log

https://pastebin.com/pKfiZ7qx

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

Prominence II [FORGE] v1.3.6

### Optifine

No

### Other Mods

I did update Ars Nouveau to fix the issue with starbuncles not taking from inventories

**Comment by THEdarkkman** [comment]
Hello there, 
Same happen for me.
Crash happen when trying to use the book into a block of some sort.
Also happen when trying to create a spell. (Giving myself the light glyph since I can't interact with the book and tries to add any component for the spell result in a crash)
Crash report 1: https://pastebin.com/e6TLTAWy
Crash report 2: https://pastebin.com/RYxBK2AD

The log were too big (I had to cut them down to fit 512kb) and pastebin flag them as potentially dangerous, so I can't post those sadly. 
If you absolutely need the logs, I can transfer via discord or something
